$(document).ready(function () {
    var table = $('#traineeTasksTable').DataTable({
        "order": [[1, "desc"]],
        "lengthMenu": [[25, 50, 75, -1], [25, 50, 75, "All"]],
        "pageLength": 50,
        "columns": [
            null, // #
            null, // Task Code
            null, // Deployed
            null, // Assignment
            null, // Status
            null, // Person
            null, // Type
            null, // Data Links (Consolidated)
            null, // Language
            null, // Updated
            null, // HRS
            { "orderable": false } // Actions column
        ]
    });

    // Event delegation: Handles clicks on expand row button (+)
    $('#traineeTasksTable tbody').on('click', '.expand-btn', function () {
        var tr = $(this).closest('tr');
        var row = table.row(tr);
        var icon = $(this);
        var taskCode = $(this).data('task-code');

        if (row.child.isShown()) {
            // Close the row
            row.child.hide();
            tr.removeClass('shown');
            icon.removeClass('fa-minus').addClass('fa-plus');
        }
        else {
            // Open the row
            if (row.child() && row.child().length) {
                // Show content already loaded in local cache
                row.child.show();
                tr.addClass('shown');
                icon.removeClass('fa-plus').addClass('fa-minus');
            } else {
                // Check if table is in public mode
                var isPublic = $('#traineeTasksTable').data('public') || '0';

                // Fetch ready HTML via AJAX from server (PHP First)
                $.ajax({
                    url: 'trainee_tasks_get_activities',
                    method: 'GET',
                    data: { task_code: taskCode, is_public: isPublic },
                    dataType: 'html',
                    success: function (htmlContent) {
                        // Directly inject content generated by PHP
                        row.child(htmlContent).show();
                        tr.addClass('shown');
                        icon.removeClass('fa-plus').addClass('fa-minus');
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr.responseText);
                        alert('Server request error.');
                    }
                });
            }
        }
    });
});
